"""Add Google Vision OCR support

Revision ID: 40685b62af08
Revises: add_grading_strictness_001
Create Date: 2025-12-09 12:54:02.900509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40685b62af08'
down_revision = 'add_grading_strictness_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip exams table - columns already exist from previous migration

    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_strategy_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('raw_response', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('bounding_boxes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('detected_language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('detected_breaks', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('page_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ocr_results_strategy', 'ocr_strategies', ['ocr_strategy_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('submission_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_result_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('extracted_bounding_box', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('extraction_method', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_submission_answers_ocr_result', 'ocr_results', ['ocr_result_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('page_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('page_count')
        batch_op.drop_column('scan_type')

    with op.batch_alter_table('submission_answers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_submission_answers_ocr_result', type_='foreignkey')
        batch_op.drop_column('extraction_method')
        batch_op.drop_column('extracted_bounding_box')
        batch_op.drop_column('ocr_result_id')

    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ocr_results_strategy', type_='foreignkey')
        batch_op.drop_column('retry_count')
        batch_op.drop_column('page_number')
        batch_op.drop_column('detected_breaks')
        batch_op.drop_column('detected_language')
        batch_op.drop_column('bounding_boxes')
        batch_op.drop_column('raw_response')
        batch_op.drop_column('ocr_strategy_id')

    # Skip exams table - columns were added in a different migration

    # ### end Alembic commands ###
