"""Add OTP table for email verification

Revision ID: 88b7fa1db830
Revises: 
Create Date: 2025-12-05 17:57:56.878725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b7fa1db830'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_code', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('otp_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('temp_user_data', sa.Text(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('attempts')
        batch_op.drop_column('purpose')
        batch_op.drop_column('otp_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_hash', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('purpose', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('attempts', sa.INTEGER(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('temp_user_data')
        batch_op.drop_column('otp_type')
        batch_op.drop_column('otp_code')

    # ### end Alembic commands ###
